# Generated by Django 4.2.3 on 2023-12-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvioCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_app.plantillacorreo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_app.usuario')),
            ],
        ),
    ]
