# Generated by Django 4.0.6 on 2023-12-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviocorreo',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
    ]
